// Türkiye İl ve İlçe Verileri
export const turkeyData = {
  "Adana": ["Seyhan", "Yüreğir", "Sarıçam", "Çukurova", "Karaisalı", "Ceyhan", "Kozan", "İmamoğlu", "Aladağ", "Feke", "Pozantı", "Saimbeyli", "Tufanbeyli", "Yumurtalık", "Karataş"],
  "Adıyaman": ["Merkez", "Besni", "Kahta", "Gölbaşı", "Gerger", "Çelikhan", "Samsat", "Sincik", "Tut"],
  "Afyonkarahisar": ["Merkez", "Sandıklı", "Dinar", "Bolvadin", "Emirdağ", "Çay", "Sultandağı", "Sinanpaşa", "İhsaniye", "Şuhut", "Dazkırı", "Başmakçı", "Bayat", "İscehisar", "Çobanlar", "Hocalar", "Evciler", "Kızılören"],
  "Ağrı": ["Merkez", "Doğubayazıt", "Patnos", "Eleşkirt", "Diyadin", "Hamur", "Taşlıçay", "Tutak"],
  "Amasya": ["Merkez", "Merzifon", "Suluova", "Taşova", "Gümüşhacıköy", "Göynücek", "Hamamözü"],
  "Ankara": ["Çankaya", "Keçiören", "Yenimahalle", "Mamak", "Etimesgut", "Sincan", "Altındağ", "Pursaklar", "Gölbaşı", "Polatlı", "Beypazarı", "Çubuk", "Haymana", "Şereflikoçhisar", "Ayaş", "Nallıhan", "Kızılcahamam", "Kalecik", "Kahramankazan", "Akyurt", "Elmadağ", "Evren", "Güdül", "Bala"],
  "Antalya": ["Muratpaşa", "Kepez", "Konyaaltı", "Alanya", "Manavgat", "Serik", "Kaş", "Kemer", "Kumluca", "Finike", "Gazipaşa", "Döşemealtı", "Aksu", "Demre", "Elmalı", "Korkuteli", "Akseki", "Gündoğmuş", "İbradı"],
  "Artvin": ["Merkez", "Hopa", "Borçka", "Arhavi", "Şavşat", "Ardanuç", "Yusufeli", "Murgul"],
  "Aydın": ["Efeler", "Nazilli", "Söke", "Kuşadası", "Didim", "Çine", "İncirliova", "Germencik", "Bozdoğan", "Sultanhisar", "Koçarlı", "Karacasu", "Buharkent", "Karpuzlu", "Köşk", "Kuyucak", "Yenipazar"],
  "Balıkesir": ["Altıeylül", "Karesi", "Bandırma", "Edremit", "Gönen", "Burhaniye", "Ayvalık", "Bigadiç", "Susurluk", "Havran", "Dursunbey", "Erdek", "Sındırgı", "İvrindi", "Manyas", "Kepsut", "Savaştepe", "Balya", "Marmara"],
  "Bilecik": ["Merkez", "Bozüyük", "Söğüt", "Osmaneli", "Gölpazarı", "Pazaryeri", "İnhisar", "Yenipazar"],
  "Bingöl": ["Merkez", "Genç", "Solhan", "Karlıova", "Adaklı", "Kiğı", "Yayladere", "Yedisu"],
  "Bitlis": ["Merkez", "Tatvan", "Ahlat", "Adilcevaz", "Hizan", "Güroymak", "Mutki"],
  "Bolu": ["Merkez", "Gerede", "Mudurnu", "Mengen", "Göynük", "Seben", "Yeniçağa", "Dörtdivan", "Kıbrıscık"],
  "Burdur": ["Merkez", "Bucak", "Yeşilova", "Gölhisar", "Tefenni", "Ağlasun", "Altınyayla", "Çavdır", "Çeltikçi", "Karamanlı", "Kemer"],
  "Bursa": ["Osmangazi", "Nilüfer", "Yıldırım", "İnegöl", "Gemlik", "Mustafakemalpaşa", "Mudanya", "Karacabey", "Orhangazi", "Kestel", "Gürsu", "İznik", "Yenişehir", "Keles", "Orhaneli", "Büyükorhan", "Harmancık"],
  "Çanakkale": ["Merkez", "Biga", "Çan", "Gelibolu", "Ayvacık", "Bayramiç", "Ezine", "Lapseki", "Yenice", "Eceabat", "Gökçeada", "Bozcaada"],
  "Çankırı": ["Merkez", "Çerkeş", "Ilgaz", "Şabanözü", "Kurşunlu", "Orta", "Yapraklı", "Atkaracalar", "Kızılırmak", "Bayramören", "Korgun", "Eldivan"],
  "Çorum": ["Merkez", "Sungurlu", "Osmancık", "Alaca", "İskilip", "Kargı", "Mecitözü", "Ortaköy", "Bayat", "Uğurludağ", "Boğazkale", "Dodurga", "Laçin", "Oğuzlar"],
  "Denizli": ["Merkezefendi", "Pamukkale", "Çivril", "Acıpayam", "Tavas", "Buldan", "Sarayköy", "Çal", "Honaz", "Kale", "Serinhisar", "Güney", "Çameli", "Bozkurt", "Çardak", "Baklan", "Beyağaç", "Babadağ"],
  "Diyarbakır": ["Bağlar", "Kayapınar", "Sur", "Yenişehir", "Bismil", "Ergani", "Çınar", "Silvan", "Dicle", "Kulp", "Hani", "Lice", "Eğil", "Hazro", "Çermik", "Çüngüş", "Kocaköy"],
  "Edirne": ["Merkez", "Keşan", "Uzunköprü", "İpsala", "Havsa", "Enez", "Süloğlu", "Meriç", "Lalapaşa"],
  "Elazığ": ["Merkez", "Kovancılar", "Karakoçan", "Palu", "Maden", "Baskil", "Sivrice", "Arıcak", "Keban", "Ağın", "Alacakaya"],
  "Erzincan": ["Merkez", "Tercan", "Üzümlü", "Refahiye", "Çayırlı", "İliç", "Kemah", "Kemaliye", "Otlukbeli"],
  "Erzurum": ["Yakutiye", "Palandöken", "Aziziye", "Horasan", "Oltu", "Pasinler", "Hınıs", "Karayazı", "Köprüköy", "Narman", "Şenkaya", "Olur", "İspir", "Tortum", "Uzundere", "Çat", "Tekman", "Karaçoban", "Pazaryolu", "Aşkale"],
  "Eskişehir": ["Odunpazarı", "Tepebaşı", "Çifteler", "Sivrihisar", "Mahmudiye", "Alpu", "Beylikova", "İnönü", "Seyitgazi", "Sarıcakaya", "Günyüzü", "Han", "Mihalgazi", "Mihalıççık"],
  "Gaziantep": ["Şahinbey", "Şehitkamil", "Nizip", "İslahiye", "Nurdağı", "Oğuzeli", "Araban", "Yavuzeli", "Karkamış"],
  "Giresun": ["Merkez", "Bulancak", "Espiye", "Görele", "Tirebolu", "Keşap", "Piraziz", "Eynesil", "Dereli", "Şebinkarahisar", "Yağlıdere", "Alucra", "Güce", "Çanakçı", "Doğankent", "Çamoluk"],
  "Gümüşhane": ["Merkez", "Kelkit", "Şiran", "Torul", "Köse", "Kürtün"],
  "Hakkari": ["Merkez", "Yüksekova", "Çukurca", "Şemdinli"],
  "Hatay": ["Antakya", "İskenderun", "Dörtyol", "Samandağ", "Kırıkhan", "Reyhanlı", "Altınözü", "Arsuz", "Belen", "Defne", "Erzin", "Hassa", "Kumlu", "Payas", "Yayladağı"],
  "Isparta": ["Merkez", "Yalvaç", "Eğirdir", "Şarkikaraağaç", "Senirkent", "Keçiborlu", "Gelendost", "Sütçüler", "Uluborlu", "Aksu", "Gönen", "Atabey", "Yenişarbademli"],
  "Mersin": ["Akdeniz", "Mezitli", "Toroslar", "Yenişehir", "Tarsus", "Erdemli", "Silifke", "Anamur", "Mut", "Gülnar", "Aydıncık", "Bozyazı", "Çamlıyayla"],
  "İstanbul": ["Kadıköy", "Üsküdar", "Maltepe", "Ataşehir", "Kartal", "Pendik", "Tuzla", "Beykoz", "Sultanbeyli", "Ümraniye", "Şile", "Çekmeköy", "Sancaktepe", "Adalar", "Fatih", "Beyoğlu", "Bakırköy", "Zeytinburnu", "Bahçelievler", "Bağcılar", "Esenler", "Küçükçekmece", "Güngören", "Başakşehir", "Avcılar", "Sultangazi", "Beylikdüzü", "Esenyurt", "Arnavutköy", "Büyükçekmece", "Çatalca", "Silivri", "Bayrampaşa", "Eyüpsultan", "Gaziosmanpaşa", "Kağıthane", "Sarıyer", "Şişli", "Beşiktaş"],
  "İzmir": ["Konak", "Bornova", "Karşıyaka", "Buca", "Bayraklı", "Çiğli", "Gaziemir", "Karabağlar", "Menemen", "Balçova", "Narlıdere", "Güzelbahçe", "Torbalı", "Ödemiş", "Bergama", "Tire", "Aliağa", "Urla", "Menderes", "Seferihisar", "Foça", "Kemalpaşa", "Dikili", "Selçuk", "Kiraz", "Bayındır", "Çeşme", "Karaburun", "Beydağ", "Kınık"],
  "Kars": ["Merkez", "Sarıkamış", "Kağızman", "Selim", "Digor", "Arpaçay", "Akyaka", "Susuz"],
  "Kastamonu": ["Merkez", "Tosya", "Taşköprü", "İnebolu", "Araç", "Cide", "Devrekani", "Küre", "Çatalzeytin", "Hanönü", "Seydiler", "Daday", "Abana", "Azdavay", "Pınarbaşı", "İhsangazi", "Şenpazar", "Ağlı", "Doğanyurt", "Bozkurt"],
  "Kayseri": ["Melikgazi", "Kocasinan", "Talas", "Develi", "Yahyalı", "Bünyan", "Pınarbaşı", "Yeşilhisar", "Tomarza", "Sarıoğlan", "Hacılar", "İncesu", "Sarız", "Felahiye", "Akkışla", "Özvatan"],
  "Kırklareli": ["Merkez", "Lüleburgaz", "Babaeski", "Vize", "Pınarhisar", "Demirköy", "Pehlivanköy", "Kofçaz"],
  "Kırşehir": ["Merkez", "Kaman", "Mucur", "Çiçekdağı", "Akpınar", "Boztepe", "Akçakent"],
  "Kocaeli": ["İzmit", "Gebze", "Darıca", "Körfez", "Derince", "Gölcük", "Karamürsel", "Kandıra", "Dilovası", "Başiskele", "Çayırova", "Kartepe"],
  "Konya": ["Selçuklu", "Meram", "Karatay", "Ereğli", "Akşehir", "Beyşehir", "Seydişehir", "Çumra", "Ilgın", "Cihanbeyli", "Karapınar", "Kulu", "Sarayönü", "Kadınhanı", "Doğanhisar", "Hüyük", "Bozkır", "Yunak", "Hadim", "Taşkent", "Derebucak", "Altınekin", "Derbent", "Emirgazi", "Güneysınır", "Halkapınar", "Çeltik", "Ahırlı", "Tuzlukçu", "Akören", "Yalıhüyük"],
  "Kütahya": ["Merkez", "Tavşanlı", "Simav", "Gediz", "Emet", "Domaniç", "Altıntaş", "Aslanapa", "Dumlupınar", "Hisarcık", "Pazarlar", "Çavdarhisar", "Şaphane"],
  "Malatya": ["Battalgazi", "Yeşilyurt", "Doğanşehir", "Akçadağ", "Darende", "Hekimhan", "Arguvan", "Pütürge", "Arapgir", "Yazıhan", "Kale", "Kuluncak", "Doğanyol"],
  "Manisa": ["Şehzadeler", "Yunusemre", "Akhisar", "Turgutlu", "Salihli", "Soma", "Alaşehir", "Demirci", "Kırkağaç", "Saruhanlı", "Kula", "Gördes", "Selendi", "Sarıgöl", "Ahmetli", "Gölmarmara", "Köprübaşı"],
  "Kahramanmaraş": ["Dulkadiroğlu", "Onikişubat", "Elbistan", "Afşin", "Türkoğlu", "Pazarcık", "Göksun", "Andırın", "Çağlayancerit", "Ekinözü", "Nurhak"],
  "Mardin": ["Artuklu", "Kızıltepe", "Nusaybin", "Midyat", "Derik", "Mazıdağı", "Ömerli", "Savur", "Dargeçit", "Yeşilli"],
  "Muğla": ["Menteşe", "Bodrum", "Fethiye", "Marmaris", "Milas", "Ortaca", "Dalaman", "Yatağan", "Köyceğiz", "Datça", "Ula", "Seydikemer", "Kavaklıdere"],
  "Muş": ["Merkez", "Bulanık", "Malazgirt", "Varto", "Hasköy", "Korkut"],
  "Nevşehir": ["Merkez", "Ürgüp", "Avanos", "Derinkuyu", "Gülşehir", "Hacıbektaş", "Kozaklı", "Acıgöl"],
  "Niğde": ["Merkez", "Bor", "Ulukışla", "Çamardı", "Altunhisar", "Çiftlik"],
  "Ordu": ["Altınordu", "Ünye", "Fatsa", "Perşembe", "Akkuş", "Gölköy", "Korgan", "Kumru", "Mesudiye", "Ulubey", "Aybastı", "Çamaş", "Çatalpınar", "Gürgentepe", "Gülyalı", "İkizce", "Kabadüz", "Kabataş"],
  "Rize": ["Merkez", "Çayeli", "Ardeşen", "Pazar", "Fındıklı", "İyidere", "Güneysu", "Derepazarı", "Çamlıhemşin", "İkizdere", "Kalkandere", "Hemşin"],
  "Sakarya": ["Adapazarı", "Serdivan", "Erenler", "Arifiye", "Hendek", "Akyazı", "Geyve", "Sapanca", "Karasu", "Pamukova", "Kaynarca", "Kocaali", "Taraklı", "Söğütlü", "Karapürçek", "Ferizli"],
  "Samsun": ["İlkadım", "Atakum", "Canik", "Tekkeköy", "Bafra", "Çarşamba", "Terme", "Vezirköprü", "Havza", "Alaçam", "Kavak", "Ladik", "Salıpazarı", "Asarcık", "Ayvacık", "Yakakent", "19 Mayıs"],
  "Siirt": ["Merkez", "Kurtalan", "Pervari", "Baykan", "Şirvan", "Eruh", "Tillo"],
  "Sinop": ["Merkez", "Boyabat", "Gerze", "Ayancık", "Durağan", "Türkeli", "Erfelek", "Dikmen", "Saraydüzü"],
  "Sivas": ["Merkez", "Şarkışla", "Zara", "Gemerek", "Suşehri", "Kangal", "Yıldızeli", "Divriği", "Gürün", "Hafik", "İmranlı", "Akıncılar", "Altınyayla", "Doğanşar", "Koyulhisar", "Ulaş", "Gölova"],
  "Tekirdağ": ["Süleymanpaşa", "Çorlu", "Çerkezköy", "Ergene", "Kapaklı", "Saray", "Hayrabolu", "Malkara", "Muratlı", "Şarköy", "Marmaraereğlisi"],
  "Tokat": ["Merkez", "Erbaa", "Turhal", "Niksar", "Zile", "Reşadiye", "Almus", "Pazar", "Yeşilyurt", "Artova", "Başçiftlik", "Sulusaray"],
  "Trabzon": ["Ortahisar", "Akçaabat", "Yomra", "Arsin", "Of", "Araklı", "Sürmene", "Vakfıkebir", "Beşikdüzü", "Çarşıbaşı", "Maçka", "Tonya", "Düzköy", "Şalpazarı", "Hayrat", "Köprübaşı", "Dernekpazarı", "Çaykara"],
  "Tunceli": ["Merkez", "Pertek", "Hozat", "Çemişgezek", "Ovacık", "Pülümür", "Mazgirt", "Nazımiye"],
  "Şanlıurfa": ["Eyyübiye", "Haliliye", "Karaköprü", "Siverek", "Viranşehir", "Suruç", "Akçakale", "Birecik", "Bozova", "Ceylanpınar", "Halfeti", "Harran", "Hilvan"],
  "Uşak": ["Merkez", "Banaz", "Eşme", "Sivaslı", "Ulubey", "Karahallı"],
  "Van": ["İpekyolu", "Tuşba", "Edremit", "Erciş", "Özalp", "Çaldıran", "Başkale", "Gevaş", "Gürpınar", "Muradiye", "Saray", "Çatak", "Bahçesaray"],
  "Yozgat": ["Merkez", "Sorgun", "Akdağmadeni", "Yerköy", "Boğazlıyan", "Sarıkaya", "Çayıralan", "Çekerek", "Aydıncık", "Çandır", "Kadışehri", "Saraykent", "Şefaatli", "Yenifakılı"],
  "Zonguldak": ["Merkez", "Ereğli", "Çaycuma", "Devrek", "Alaplı", "Gökçebey", "Kilimli", "Kozlu"],
  "Aksaray": ["Merkez", "Ortaköy", "Eskil", "Gülağaç", "Güzelyurt", "Ağaçören", "Sarıyahşi", "Sultanhanı"],
  "Bayburt": ["Merkez", "Demirözü", "Aydıntepe"],
  "Karaman": ["Merkez", "Ermenek", "Ayrancı", "Kazımkarabekir", "Başyayla", "Sarıveliler"],
  "Kırıkkale": ["Merkez", "Yahşihan", "Keskin", "Delice", "Sulakyurt", "Bahşili", "Balışeyh", "Karakeçili", "Çelebi"],
  "Batman": ["Merkez", "Kozluk", "Sason", "Beşiri", "Gercüş", "Hasankeyf"],
  "Şırnak": ["Merkez", "Cizre", "Silopi", "İdil", "Uludere", "Beytüşşebap", "Güçlükonak"],
  "Bartın": ["Merkez", "Ulus", "Amasra", "Kurucaşile"],
  "Ardahan": ["Merkez", "Göle", "Çıldır", "Hanak", "Posof", "Damal"],
  "Iğdır": ["Merkez", "Tuzluca", "Aralık", "Karakoyunlu"],
  "Yalova": ["Merkez", "Çınarcık", "Termal", "Altınova", "Armutlu", "Çiftlikköy"],
  "Karabük": ["Merkez", "Safranbolu", "Yenice", "Eflani", "Eskipazar", "Ovacık"],
  "Kilis": ["Merkez", "Elbeyli", "Musabeyli", "Polateli"],
  "Osmaniye": ["Merkez", "Kadirli", "Düziçi", "Bahçe", "Toprakkale", "Sumbas", "Hasanbeyli"],
  "Düzce": ["Merkez", "Akçakoca", "Cumayeri", "Gölyaka", "Çilimli", "Gümüşova", "Kaynaşlı", "Yığılca"]
}

// İl listesi (alfabetik sıralı)
export const cities = Object.keys(turkeyData).sort((a, b) => a.localeCompare(b, 'tr'))

// İlçe getirme fonksiyonu
export const getDistricts = (city) => {
  return turkeyData[city] || []
}